---
all: 
   vars:
       ansible_python_interpreter: /usr/bin/python3

prod:
   vars: 
       ansible_user: "{{ user }}"
       ansible_password: "{{ password }}"
       ansible_ssh_common_args: -o StrictHostKeyChecking=no
       ansible_sudo_pass: "{{ password }}"
       env: "production"
   hosts:  
    server1: 
       ansible_host: 172.20.0.2
