version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com   # L'email par défaut pour l'admin
      - PGADMIN_DEFAULT_PASSWORD=admin          # Le mot de passe par défaut pour l'admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin          # Persistance des données pgAdmin
      - ./config:/pgadmin4/config              # Persistance du fichier servers.json
    ports:
      - "5050:80"  # Accès à pgAdmin sur le port 5050 de l'hôte
    networks:
      - pg_network
    restart: always

volumes:
  pgadmin_data:
    driver: local

networks:
  pg_network:
    driver: bridge
